#! /bin/sh


m0=$(xrandr -q | grep DP-0)
m1=$(xrandr -q | grep DP-1)


xrandr --output m0 --auto --primary && -z "$m1" || xrandr --output m1 --auto --right-of m0


if ! echo "$mainmonitor" | grep LVDS >/dev/null 2>&1; then 
	xrandr --output "$mainmonitor" --auto --output LVDS1 --off
fi


bspc config border_width 3;
bspc config window_gap 6;
bspc config top_padding 23;
bspc config focus_follows_pointer true


##Color settings
bspc config focused_border_color "#1ABB9B"
bspc config normal_border_color "#222D32"
#"#000000"
bspc config presel_feedback_color "#1ABB9B"
#"#8F3724"

#Settings for manual splitting
bspc config split_ratio         0.52


bspc monitor DP-0 -d 1 2 3 4 5 6 7 8 9
bspc monitor DP-1 -d 0

#bspc monitor -d I II III IV V VI VII VIII IX X
bspc desktop -f I

###External rules
##Pseudo automatic mode: always splits focused window when opening new window
bspc config external_rules_command /usr/bin/pseudo_automatic_mode
##Adjust new window: splits biggest windows to keep windows about the same size
#bspc config external_rules_command /usr/bin/adjust-new-window


$HOME/.config/polybar/launch.sh

# Alter compton settings if using intel graphics
GRAPHIC_CARD=$(lspci | grep -i "vga" | sed 's/.*://' | sed 's/(.*//' | sed 's/^[ \t]*//')
if [[ $(echo $GRAPHIC_CARD | grep -i 'intel\|lenovo') != "" ]]; then MCODE='initrd=\intel-ucode.img'
  sed -i 's/"xrender"/"glx"/' ~/.config/picom.conf
  grep -q 'vsync = "opengl-swc";' ~/.config/picom.conf || echo 'vsync = "opengl-swc";' >> ~/.config/picom.conf
fi
